### ISSUE TITLE
RFC: Shift theme selection into a separate module

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-cms#1552]
With the recent work on cascading themes, we have created a situation where a lot of themes are available in an install that aren't relevant for a "select a theme" dropdown in the SiteConfig.

Not every site has been built to allow users to switch between more than 1 appropriate theme. This is an important feature for certain use-cases (e.g. if you have a micro-site platform where a client can spin up new sites with a known feature set, or a platform for letting users build their site without developer assistance).

We should recognise this is a helpful set of training wheels for newcomers to SilverStripe, but is unlikely to be in common use for more serious SilverStripe deployments.

Therefore I think that theme selection should be split into a module. The module should be a dependency of `silverstripe/installer` but not `silverstripe/cms`. This means that it's provided by default but is easily removed if people don't need it.
## Details

The `silverstripe/user-theme-selector` module would provide configuration for `UserThemeList` that let you indicate which themes would be presented to a user:

You could ask to include everything and remove some items with a blacklist:

``` yaml
SilverStripe\UserThemeSelector\UserThemeList:
  include_all: true
  blacklist:
    - themename
```

Or you could specify only those themes that you are interested in displaying:

``` yaml
SilverStripe\UserThemeSelector\UserThemeList:
  include_all: false
  whitelist:
    "Excellent Theme": themename
    "Bootstrap-based Theme": [ othertheme, bootstrapforms ]
```
## Short-term

In the short term, I think it is acceptable to simply remove this feature from the siteconfig module.
## Alternatives
- **Add more configuration options to core** I feel that this is bloat for secondary use-case, and I'm increasingly taking the view that "if it can be modular, then it should be"
- **Remove the feature entirely** I don't want to neglect newcomers entirely. 
- **Keep the feature listing all themes, including framework:admin/cms-forms** This will confuse users.
- **Only list those themes included in the root themes folder** This is a hangover from SS3 and I'd expect that at some stage we'll treat themes just like regular modules, and so this will stop working.
- **Don't make this a default module** I think that the list of modules in installer should be optimised for newcomers, and newcomers would benefit from this module.
