### ISSUE TITLE
CMS content actions not visible in Safari 10.0.1

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-cms#1674]
This seems to effect SS4-alpha3
There seems to be a flexbox bug safari causing the action bar to render bellow the bottom of the viewport. Adding max-height to the .cms-content-fields div above it seems to fix the issue, though it seems a little hackey.

```css
.cms .cms-content-fields {
    overflow-y: auto;
    background: transparent;
    max-height: calc(100vh - 53px - 53px);
}
```
