### ISSUE TITLE
How to disable extension by overriding yml config file?

### ISSUE THREAD

**Issue by micobarac** [silverstripe/silverstripe-cms#2146]
If some extension adds itself to `SiteTree` through the extension's `*.yml` config file, how do I disable the extension for `SiteTree` and allow it only for a custom `MyClass` by overriding, using custom `*.yml `config file in `mysite/_config` location?

I don't want to change the original extension's config file, for the sake of future upgrades.

**Comment by dhensby** [comment]
i think this is the only way to do it, are you using the FQCN when passing it to `remove_extension`?

**Comment by micobarac** [comment]
Yes, I am using FQCN.

**Comment by micobarac** [comment]
There should be a feature to do this via `*yml` files in the future.

**Comment by dhensby** [comment]
If you're talking about the comments yml - that's not true, you can apply your yml to the extension directly rather than to the target class.

**Comment by micobarac** [comment]
What do you mean by applying yml to extension directly? I go to the extension `_config` folder i change `yml` file?

**Comment by robbieaverill** [comment]
I think if the extension has a key then you can set it to falsy (in SS4), e.g.

```yml
MyClass:
  extensions:
    MyExtensionAlias: My\Extension\ClassName
```

Then:
```yml
---
Name: myconfig
After: '#originalconfig'
---
MyClass:
  extensions:
    MyExtensionAlias: false
```

If you are just pushing an array with no keys then config will be merged and you will need to use PHP to remove it

**Comment by micobarac** [comment]
This is the original extension yml partial content:

```yml
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
```

**Comment by robbieaverill** [comment]
If you modify the comments YAML file so it has an alias, are you able to remove it again via that alias?

**Comment by micobarac** [comment]
Yes, I can modify the comments `yaml `file, and change `SiteTree `into `BlogPost`. That's the easiest way. But I don't think that original extensions should be changed, but overriden instead, in case we need it.

**Comment by tractorcow** [comment]
There in an awkward hack you can use to do this.

```
---
name: resetextensions
---
SilverStripe\CMS\Model\SiteTree:
  extensions: null
---
name: restoresomeextensions
after: '#resetextensions'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\ORM\Hierarchy\Hierarchy
    - SilverStripe\Versioned\Versioned
    - SilverStripe\Security\InheritedPermissionsExtension
```

This will clear all extensions, letting you re-add back only the ones you want to keep on SiteTree.

**Comment by tractorcow** [comment]
For comments modurle, we could do this

```yaml
SilverStripe\CMS\Model\SiteTree:
  extensions:
    comments: SilverStripe\Comments\Extensions\CommentsExtension
```

This would allow you to disable that extension with only this code


```
SilverStripe\CMS\Model\SiteTree:
  extensions:
    comments: null
```
