### ISSUE TITLE
Cannot embed YouTube link on CWP

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2168]
Environment:
* mediumtest-uat on CWP
* SilverStripe 4.1.0
* CWP 2.0-rc3

Steps:

* Go to a CMS page
* Click on "Insert media via URL"
* Paste a link to a YouTube video
* Hit "Add media"

Expected:

* Video will be embedded into TinyMCE content

Actual:

* Network request fails with 503 Service Temporarily Unavailable
* Media dialog shows an error

![image](https://user-images.githubusercontent.com/5170590/40095717-a47d1992-5921-11e8-9465-e6099a4cea55.png)

![image](https://user-images.githubusercontent.com/5170590/40095746-bc4bd4a0-5921-11e8-8856-6709e23343fd.png)

---

Reported by @emteknetnz via SilverStripe Ops, supposedly works correctly on localhost. This could possibly be an Incapsula issue?

---

## Pull requests

- [x] 4.1: https://github.com/silverstripe/silverstripe-framework/pull/8192
- [x] 4.1: https://github.com/silverstripe/silverstripe-asset-admin/pull/793
- [x] CWP 2.0: https://github.com/silverstripe/cwp-recipe-cms/pull/8
- [x] 4.2: https://github.com/silverstripe/silverstripe-framework/pull/8194
- [ ] 4.2: https://github.com/silverstripe/silverstripe-asset-admin/pull/795
- [x] CWP 2.1: https://github.com/silverstripe/cwp-recipe-cms/pull/9

**Comment by indygriffiths** [comment]
When this issue initially was raised with RC's our first guess was that the request isn't being correctly passed through the [CWP proxy](https://www.cwp.govt.nz/developer-docs/en/2/how_tos/external_http_requests_with_proxy/) given the error message. 

The docs state that `By default, we configure the PHP environment with http_proxy and https_proxy variables which will be automatically picked up by curl` so it would be worth checking to see if the framework is making the request by some other means that may not use those variables (does Guzzle?)

**Comment by caffeineinc** [comment]
I created a pull request on silverstripe-asset-admin which hopefully would address the underlying issue. We'd still need to reference that somewhere in the CWP recipe. 

https://github.com/silverstripe/silverstripe-asset-admin/pull/793

**Comment by robbieaverill** [comment]
All PRs added to issue description

**Comment by lukereative** [comment]
@robbieaverill All reviewed so should be good for a core committer to merge them all

**Comment by robbieaverill** [comment]
Thanks @lukereative

**Comment by robbieaverill** [comment]
All PRs merged, fixes will be available in 4.1.x and 4.2.x

**Comment by katieelks** [comment]
We are getting this issue again, confirmed in a couple of environments. Is this a regression perhaps?

**Comment by robbieaverill** [comment]
Confirmed the regression with CWP 2.1.1-rc2. I'll investigate further today.

**Comment by robbieaverill** [comment]
Sorry, I'm mistaken. I can't reproduce this any longer on CWP 2.1.1-rc2.

@katieelks can you please ask one of your devs to add the missing error logging configuration from CWP 2.x (see https://github.com/silverstripe/cwp-core/issues/43) and re-deploy, then try again? This should mean you get some debugging information in Graylog.

**Comment by brynwhyman** [comment]
For reference: after a few iterations, a fix that was originally applied to config in cwp-recipe-cms was moved to cwp-core to ensure it would be picked up by all CWP sites regardless of other modules that are installed. This was released for CWP 2.1.1.

See https://github.com/silverstripe/cwp-recipe-cms/issues/11

**Comment by sunnysideup** [comment]
We have CWP 2.1 installed:

in cwp-recipe-cms:
```yml
---
Name: cwpoembedconfig
After: coreoembed
Except:
  environment: dev
Only:
  EnvVarSet: SS_OUTBOUND_PROXY
---
SilverStripe\Core\Injector\Injector:
  # Configure the CWP proxy if defined
  Embed\Http\DispatcherInterface:
    class: Embed\Http\CurlDispatcher
    constructor:
      config:
        # CURLOPT_PROXY = 10004
        10004: '`SS_OUTBOUND_PROXY`'
        # CURLOPT_PROXYPORT = 59
        59: '`SS_OUTBOUND_PROXY_PORT`'

  # Provide dispatcher to Embeddable implementations
  SilverStripe\View\Embed\Embeddable:
    properties:
      Dispatcher: '%$Embed\Http\DispatcherInterface'

```

so:
* not yet in core
* not working ;-( despite config being present
