### ISSUE TITLE
SilverStripe 4.1.x and Silverstripe-S3 module - TinyMCE WYSIWYG doesn't load on initial CMS Load

### ISSUE THREAD

**Issue by obj63mc** [silverstripe/silverstripe-cms#2177]
Currently testing using v4.1.x and dev/master of silverstripe-s3.

I wasn't sure where the best place to log this issue but assuming it will probably need to be moved to a fix in silverstripe/framework as it is an issue with the HTMLEditorField, or possibly needs to go to the silverstripe-s3 repo.

# Steps to reproduce
1. Create a clean install of SS4.x using the composer command - 

            composer create-project silverstripe/installer /path/to/project 4.1.1
2. Configure the site as normal and require silverstripe-s3 

            composer require silverstripe/silverstripe-s3

3. Complete configuration of S3
4. Go to your site/admin and login
5. Edit the Home Page-  I get the following JS error - 

        bundle.js?m=1520903238:1 Uncaught ReferenceError: tinymce is not defined
            at Object.create (bundle.js?m=1520903238:1)
            at Object.init (bundle.js?m=1520903238:1)
            at init.onadd (bundle.js?m=1520903238:1)
            at o (vendor.js?m=1520903238:1)
            at Array.<anonymous> (vendor.js?m=1520903238:1)
            at HTMLDocument.<anonymous> (vendor.js?m=1520903238:1)
            at HTMLDocument.dispatch (eval at t.exports (vendor.js?m=1520903238:1), <anonymous>:3332:9)
            at HTMLDocument.eventHandle (eval at t.exports (vendor.js?m=1520903238:1), <anonymous>:2941:28)
            at Object.trigger (eval at t.exports (vendor.js?m=1520903238:1), <anonymous>:3210:12)
            at init.triggerHandler (eval at t.exports (vendor.js?m=1520903238:1), <anonymous>:3874:24)

Screen shot - 
![screen shot 2018-05-29 at 4 23 58 pm](https://user-images.githubusercontent.com/443120/40686377-b9425afa-635c-11e8-874f-51fac9677307.png)

I notice though that in my network console it is trying to load the tinymce script from the amazon public directory, not the local server address - example : 

        ....s3.amazonaws.com/public/_tinymce/tinymce-cms-92563982d3.js?_=1527628916905 

vs 
        /assets/_tinymce/tinymce-cms-92563982d3.js?_=1527628916905

Since this is loading the tinymce script file from S3 not sure if that is the cause of a race condition, cross domain origin issue or ?

If I refresh the page in the browser (eg /admin/pages/edit/show/1), the CMS loads normally and the WYSIWYG loads normally.  If I go to a different section of the CMS besides pages though such as say 'Settings' and then back to pages I get the same issue until I reload the site.

Is this possibly an issue as the file is being generated into the /public/assets directory instead of the /public/resources directory?  If there is a way to exclude this file from loading on S3 or a way to change the write path for the tinymce js I can test this some more to try and confirm what exactly is causing the issue.

**Comment by maxime-rainville** [comment]
The `silverstripe/s3` module is experimental. It's not something we're actively working on at this time.

**Comment by obj63mc** [comment]
As a note, I turned off and removed the S3 module and still have the same issue.  So not 100% sure it is caused by that module.

**Comment by anishpixel** [comment]
I am having the same issue, I am using webpack for my web build too so think something is conflicting.

**Comment by spark-green** [comment]
Hi guys,
I am having the same issue, 
I am not using  S3 module. but using webpack to run foundation on front-end.

And surprising it is happening only with one single page in CMS.
screenshot 

![image](https://user-images.githubusercontent.com/2790964/43430106-9c78599a-94aa-11e8-9fd3-72c16be1c036.png)

Console error as below
![image](https://user-images.githubusercontent.com/2790964/43430058-6c1b3e3e-94aa-11e8-8018-cb7f74f3160f.png)


Any help on this is much appreciated.

**Comment by jpmcc** [comment]
Also experiencing similar issue. However, I _am_ using the S3 module, and _not_ using Webpack. The TinyMCE script is being loaded from S3.

Just currently trying to work out why that is placed into assets when all other admin JS isn't

**Comment by anishpixel** [comment]
No reply from SS mods or contributors? Seems odd to avoid this as various people are having this issue...

**Comment by jpmcc** [comment]
It looks to be a timing thing. The script `tinymce-cms-<unique-string>.js` is  actually loaded from S3, but I am guessing it is after it is actually called. I assume that is why if the page is reloaded, it appears to work as it is now already in the cache. However going back some time later, it is requested again but with a cache busting parameter.

I can see why it is generated as it references the site domain to setup a `baseUrl` var.

Just wondering what can be done about that.

Not totally sure if this fits in with everyone else's experience if not using the S3 module.

**Comment by jpmcc** [comment]
When reloading, the requirements system places the call for the script into the page source, as you would expect, therefore I assume everything blocks until all the scripts have loaded, and everything works.

Navigating within the CMS, when you move to an area that requires the TinyMCE editor, the JavaScript requirements are pulled in via Ajax and an`x-include-js` header. I assume there is some timing issue here between the script being requested and the editor trying to load, but before the script has loaded in, hence the `tinymce is not defined` error.

Is there any way of forcing the request for the TinyMCE script earlier, or delaying the editor from trying to initialise for a bit longer?

**Comment by jpmcc** [comment]
Is there a way to configure the Requirements system to place the TinyMCE generated file to a local folder? There is some information on requirements about[ changing where combined assets are placed](https://docs.silverstripe.org/en/4/developer_guides/templates/requirements/#configuring-combined-file-storage), but so far not making any headway with that.

**Comment by jpmcc** [comment]
No idea. I can see the file contents are loaded by the browser, but obviously too late to prevent the `undefined` error.

I was just wondering if there was a way to override the tinymce file being placed in assets, but elsewhere - by using the method outlined int he requirements documentation. I know that kind of defeats the purpose of having assets somewhere like S3, but just kind of clutching at straws at the moment.

**Comment by kinglozzer** [comment]
You _might_ be able to override the asset handler for TinyMCE generated files. Totally untested code below, but it might provide a starting point:

```yml
SilverStripe\Core\Injector\Injector:
  League\Flysystem\Filesystem.localpublic:
    class: League\Flysystem\Filesystem
    constructor:
      FilesystemAdapter: '%$SilverStripe\Assets\Flysystem\PublicAssetAdapter'
      FilesystemConfig:
        visibility: public
  LocalGeneratedAssetHandler:
    class: SilverStripe\Assets\Flysystem\GeneratedAssets
    properties:
      Filesystem: '%$League\Flysystem\Filesystem.localpublic'
  SilverStripe\Forms\HTMLEditor\TinyMCECombinedGenerator:
    properties:
      AssetHandler: '%$LocalGeneratedAssetHandler'
```

**Comment by jpmcc** [comment]
Thanks Loz, I think I was going down the same path based on the docs, but I think I'm still missing something. The `GeneratedAssetHandler` being injected into the TinyMCE generator still uses the `SilverStripe\S3\Adapter\PublicCacheAdapter` as the Adaptor.

**Comment by jpmcc** [comment]
Not sure the configuration is even being picked up :-(. Created a `yml` file in the `_config` folder. I would expect to see an instance of `League\Flysystem\Filesystem` being created. The only one that triggers the constructor is for the `S3` adapter.

Therefore I'm assuming I am missing something pretty fundamental. All my other `yml` files appear to be processed (multiple builds and flushes).

**Comment by kinglozzer** [comment]
Maybe you need a YAML header to ensure it’s loaded last

```yml
---
After:
  - '#corehtml'
---
SilverStripe\Core\Injector\Injector:
  League\Flysystem\Filesystem.localpublic:
# ...
```

**Comment by jpmcc** [comment]
yup, using 
```
---
Name: tinymce_override
After:
  - '#silverstripes3-flysystem'
---
```
I'll try `#corehtml`

**Comment by jpmcc** [comment]
No luck. 

Really appreciate the help :)

**Comment by kinglozzer** [comment]
The following does seem to work in my testing - `App\TestAssetAdapter` is the adapter used in `TinyMCECombinedGenerator`:

```yml
---
After:
  - '#corehtml'
---
SilverStripe\Core\Injector\Injector:
  League\Flysystem\Filesystem.localpublic:
    class: 'League\Flysystem\Filesystem'
    constructor:
      FilesystemAdapter: '%$App\TestAssetAdapter'
      FilesystemConfig:
        visibility: public
  LocalGeneratedAssetHandler:
    class: 'SilverStripe\Assets\Flysystem\GeneratedAssets'
    properties:
      Filesystem: '%$League\Flysystem\Filesystem.localpublic'
  SilverStripe\Forms\HTMLEditor\TinyMCECombinedGenerator:
    properties:
      AssetHandler: '%$LocalGeneratedAssetHandler'
```

```php
namespace App;

use SilverStripe\Assets\Flysystem\PublicAssetAdapter;

class TestAssetAdapter extends PublicAssetAdapter
{
}
```

Probably best at this point to hop on the [forums](https://forum.silverstripe.org/) or [Slack](https://www.silverstripe.org/community/slack-signup/) to save adding any more to this issue 😄
