### ISSUE TITLE
modelascontrollerroutes config block creates infinite loop when trying to override

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-cms#2222]
**Version: CWP 2.1.0 (SilverStripe 4.2.0)**

The routes.yml in CMS has this:

```yaml
---
Name: modelascontrollerroutes
After: '*'
---
SilverStripe\Control\Director:
  rules:
    '': 'SilverStripe\CMS\Controllers\RootURLController'
    'RemoveOrphanedPagesTask//$Action/$ID/$OtherID': 'SilverStripe\CMS\Tasks\RemoveOrphanedPagesTask'
    'SiteTreeMaintenanceTask//$Action/$ID/$OtherID': 'SilverStripe\CMS\Tasks\SiteTreeMaintenanceTask'
    '$URLSegment//$Action/$ID/$OtherID': 'SilverStripe\CMS\Controllers\ModelAsController'
```

I want to overload the `''` route:

```yaml
---
Name: myroutes
After: '#modelascontrollerroutes'
---
SilverStripe\Control\Director:
  rules:
    '': MyController
```

This creates an infinite config loop.

```
Fatal error: Uncaught exception 'MJS\TopSort\CircularDependencyException' with message 'Circular dependency found: myroutes->modelascontrollerroutes->o' in .../dev/demo/core/vendor/marcj/topsort/src/CircularDependencyException.php on line 34
```

We should change the CMS `After` to specify what it needs to be after. Using `*` is not a good idea in SilverStripe 4.
