### ISSUE TITLE
ModelAdmin 'Update URL' Button

### ISSUE THREAD

**Issue by PVerberkmoes** [silverstripe/silverstripe-cms#2608]
Hello everyone, 

I am using a ModelAdmin for my Pages and i saw that the 'Update URL' text of the button is not showing.
When i use a normal Page it is shown.

This is inside and page of an ModelAdmin
![Screenshot 2020-11-03 at 15 07 57](https://user-images.githubusercontent.com/25683222/97998545-883a3180-1dea-11eb-9917-03d20ca23d8e.png)

And this is inside an Page
![Screenshot 2020-11-03 at 15 38 31](https://user-images.githubusercontent.com/25683222/97998621-a2740f80-1dea-11eb-9e8e-4058d1cda729.png)

Here is an example of my ModelAdmin

```
<?php 

use SilverStripe\Admin\ModelAdmin;

class NewsAdmin extends ModelAdmin {
	
    private static $managed_models = [
         NieuwsPage::class => [
            'title' => 'Nieuws'
	]
    ];

    private static $url_segment = 'Nieuws';
    private static $menu_title = "Nieuws";
    private static $menu_icon_class = 'font-icon-p-archive';
}
```

**Comment by lerni** [comment]
not a fix but a single language workaround:
```scss
#Form_ItemEditForm_Title_Holder {
	.form__field-update-url {
		&:after {
			content: 'Update URL';
		}
	}
	// prevent description being shown inline
	.form__field-description {
		width: 100%;
	}
}
```
