### ISSUE TITLE
"Preview mode" bug: Page reloads after navigation

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-cms#2756]
When editing a page in the CMS, if you open "Preview mode" and then click a link to navigate to another page, the new page loads, but then immediately reloads a split second later.

On some sites this is more noticeable than others, and on sites with on-load transitions, it is especially annoying as it looks like the transition occurs twice.

It seems to be related to the presence of `$MetaTags(false)` in the template, as if you remove this line the reload issue doesn't occur.

This can be easily reproduced in a clean Silverstripe 4.11.0 install. To make the issue more obvious, you can add a transition to the body, e.g. add this to the `head` in `templates/Page.ss`.

````css
<style>
	@keyframes slideInFromLeft { 0% { transform: translateX(-100%);} 100% {transform: translateX(0);}}
	body { animation: 0.5s ease-out 0s 1 slideInFromLeft;}
</style>
````

Here you can see the pages load twice:

![Screenshot 2022-07-28 at 14 18 19](https://user-images.githubusercontent.com/329880/181515070-e7df3051-f613-4b0f-a964-77f92e627ce8.gif)

If you remove `$MetaTags(false)` the issue goes away:

![Screenshot 2022-07-28 at 14 20 48](https://user-images.githubusercontent.com/329880/181515511-342a12c6-9376-4ab8-bbe2-0dfb1ac87c4a.gif)
